apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-declarative-config
  namespace: kong  # Ensure this matches the Kong namespace
  labels:
    app: kong-kong
data:
  kong.yml: |
    _format_version: "3.0"
    services:
      - name: example_service
        url: http://example.com
    routes:
      - name: example_route
        service: example_service
        paths:
          - /example
