apiVersion: v1
kind: Service
metadata:
  name: neo4j-graphs-service
spec:
  selector:
    app: neo4j-graphs
  ports:
  - protocol: TCP
    port: 7474
    targetPort: 7474
    name: http
    nodePort: 31744
  - protocol: TCP
    port: 7687
    targetPort: 7687
    name: bolt
    nodePort: 31250
  type: NodePort
