---
- name: Install cifs-utils and jq packages on Ubuntu 22
  hosts: k8s-int-cluster
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install cifs-utils package
      apt:
        name: cifs-utils
        state: present

    - name: Install jq package
      apt:
        name: jq
        state: present

